### ISSUE TITLE
Suggestions & Ideas

### ISSUE THREAD

**Issue by huthaifa-abd** [huthaifa-abd/RustBeast-Game-Server#1]
Feel free to suggest a feature or required item for your game , we are developing this as we go so there might some early or later features for this and it highly depends on the team requirements

**Comment by eng-ali** [comment]
test hello world

**Comment by AbdullahAlimam** [comment]
we should start with designing the database. and take our time with the base structure then we can develop as we go.

so at first we need to name the man data that we need to store in database. like
Scores
Items
Points
Money
Money types [Coin, Jewels, Green Money .. etc]
.... etc

after that we can start with a base database before we go

**Comment by eng-ali** [comment]
yes exactly

**Comment by huthaifa-abd** [comment]
Sure lets do that , ill prepare the basic code for CRUD operations , @AbdullahAlimam  see if u can handle the database design since you have already created something similar

**Comment by huthaifa-abd** [comment]
@eng-ali administrators would require a graphical c-panel to review the player progress and see statistics can you handle the front end design and the API integration
